@Back_HostAddress = http://localhost:5251

# Test Auth Login
POST {{Back_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "nombreUsuario": "admin",
  "contrasena": "123456"
}

###

# Test Swagger
GET {{Back_HostAddress}}/swagger
Accept: text/html

###
